[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "rm -rf node_modules && bun install && bun run build"
  publish = ".next"

[build.environment]
  NEXT_LINT_SKIP = "true"
  SKIP_ESLINT = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Force cache clear
